FROM node:18-bullseye
RUN apt-get update && apt-get install -y \
    less \
    vim \
    netcat \
    iproute2 \
    telnet \
    && rm -rf /var/lib/apt/lists/*
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
RUN chown -R node:node /opt/
USER node
WORKDIR /opt/
COPY --chown="node:node" ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
WORKDIR /opt/app/src/plugins/lookup
COPY --chown="node:node" src/plugins/lookup/package.json src/plugins/lookup/package-lock.json ./
RUN npm install
ENV PATH /opt/app/src/plugins/lookup/node_modules/.bin:$PATH
WORKDIR /opt/app
COPY --chown="node:node" ./ .
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]   
