name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Create .env
      run: cp .env.example .env
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag strapi-rpb:$(date +%s)
